# Generated by Django 5.1.2 on 2024-11-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_record_ne_alter_record_caller_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='caller_address',
        ),
        migrations.AddField(
            model_name='record',
            name='caller_house_number',
            field=models.CharField(blank=True, default='Não Informado', max_length=5),
        ),
        migrations.AddField(
            model_name='record',
            name='caller_neighborhood',
            field=models.CharField(blank=True, default='Não Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='caller_street',
            field=models.CharField(blank=True, default='Não Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='caller_zip_code',
            field=models.CharField(blank=True, default='Não Informado', max_length=9),
        ),
    ]
