# Generated by Django 5.1.2 on 2024-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_record_caller_house_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='ambulance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='are_there_victims',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='bopc',
            field=models.CharField(blank=True, default='Não Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='child_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='incident_conclusion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='incident_dispatch_VTR',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='incident_house_number',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='incident_neighborhood',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='incident_zip_code',
            field=models.CharField(default='0', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='is_there_a_firearm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='joint_operation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='nature_of_the_incident',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='notification_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='number_of_people_involved',
            field=models.CharField(blank=True, default='Não Informado', max_length=15),
        ),
        migrations.AddField(
            model_name='record',
            name='officer_in_charge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='officer_in_charge_actions',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='record',
            name='police_chief_qra',
            field=models.CharField(blank=True, default='Não Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='police_district',
            field=models.CharField(blank=True, default='Não Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='priority_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='reference_point',
            field=models.CharField(blank=True, default='Não Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='response_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='ri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='ro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='suspect_approximate_age',
            field=models.CharField(blank=True, default='Não Informado', max_length=15),
        ),
        migrations.AddField(
            model_name='record',
            name='suspect_approximate_height',
            field=models.CharField(blank=True, default='Não Informado', max_length=15),
        ),
        migrations.AddField(
            model_name='record',
            name='suspect_description',
            field=models.CharField(blank=True, default='Não Informado', max_length=254),
        ),
        migrations.AddField(
            model_name='record',
            name='suspect_haircut_style',
            field=models.CharField(blank=True, default='Não Informado', max_length=15),
        ),
        migrations.AddField(
            model_name='record',
            name='suspect_skin_color',
            field=models.CharField(blank=True, default='Não Informado', max_length=15),
        ),
        migrations.AddField(
            model_name='record',
            name='suspect_tatoos',
            field=models.CharField(blank=True, default='Não Informado', max_length=254),
        ),
        migrations.AddField(
            model_name='record',
            name='type_of_incident',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle',
            field=models.CharField(blank=True, default='Não se aplica', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_color',
            field=models.CharField(blank=True, default='Não se aplica', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_model',
            field=models.CharField(blank=True, default='Não se aplica', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_type',
            field=models.CharField(blank=True, default='Não se aplica', max_length=100),
        ),
    ]
