# Generated by Django 5.1.2 on 2024-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_record_incident_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
